ALTER TABLE accounts
    ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN last_login_at TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE authentication_methods
    ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN last_used_at TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN token_expiry TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE roles
    ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE refresh_tokens
    ALTER COLUMN expires_at TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN revoked_at TYPE TIMESTAMP WITH TIME ZONE;