<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Version>1.0.0</Version>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Turboapi.Geo</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
        <PackageReference Include="Medo.Uuid7" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" />
        <PackageReference Include="NetTopologySuite" />
        <PackageReference Include="NetTopologySuite.IO.GeoJSON" />
        <PackageReference Include="Newtonsoft.Json" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL.NetTopologySuite" />
        <PackageReference Include="Npgsql.NetTopologySuite" />
        <PackageReference Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" />
        <ProjectReference Include="../TurboAuthentication/TurboAuthentication.csproj" />
        <ProjectReference Include="../src/Shared/Turbo.Outbox.Postgres/Turbo.Outbox.Postgres.csproj" />
        <ProjectReference Include="../src/Shared/Turbo.Messaging.Nats/Turbo.Messaging.Nats.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Microsoft.AspNetCore.Builder" />
        <Using Include="Microsoft.AspNetCore.Hosting" />
        <Using Include="Microsoft.AspNetCore.Http" />
        <Using Include="Microsoft.AspNetCore.Routing" />
        <Using Include="Microsoft.Extensions.Configuration" />
        <Using Include="Microsoft.Extensions.DependencyInjection" />
        <Using Include="Microsoft.Extensions.Hosting" />
        <Using Include="Microsoft.Extensions.Logging" />
    </ItemGroup>

</Project>
