apiVersion: apps/v1
kind: Deployment
metadata:
  name: turboapi-auth
spec:
  template:
    spec:
      containers:
        - name: turboapi-auth
          env:
            # Add CORS Configuration
            - name: AllowedOrigins
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: CORS__AllowedOrigins
            # Add JWT Configuration
            - name: Jwt__Key
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: jwt-key
            - name: Jwt__Issuer
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: Jwt__Issuer
            - name: Jwt__Audience
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: Jwt__Audience
            - name: Jwt__TokenExpirationMinutes
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: Jwt__TokenExpirationMinutes
            - name: Jwt__RefreshTokenExpirationDays
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: Jwt__RefreshTokenExpirationDays
            # Add Google Auth Configuration
            - name: Authentication__Google__ClientId
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: google-client-id
            - name: Authentication__Google__ClientSecret
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: google-client-secret
            - name: Authentication__Google__RedirectUri
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: Authentication__Google__RedirectUri
            - name: Authentication__Google__TokenInfoEndpoint
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: Authentication__Google__TokenInfoEndpoint
---
# geo-deployment-patch.yaml - Add to your overlays/prod folder
apiVersion: apps/v1
kind: Deployment
metadata:
  name: turboapi-geo
spec:
  template:
    spec:
      containers:
        - name: turboapi-geo
          env:
            # Add CORS Configuration
            - name: AllowedOrigins
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: CORS__AllowedOrigins
            # Add JWT Configuration for validation
            - name: Jwt__Key
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: jwt-key
            - name: Jwt__Issuer
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: Jwt__Issuer
            - name: Jwt__Audience
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: Jwt__Audience
---
# activity-deployment-patch.yaml - Add to your overlays/prod folder
apiVersion: apps/v1
kind: Deployment
metadata:
  name: turboapi-activity
spec:
  template:
    spec:
      containers:
        - name: turboapi-activity
          env:
            # Add CORS Configuration
            - name: AllowedOrigins
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: CORS__AllowedOrigins
            # Add JWT Configuration for validation
            - name: Jwt__Key
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: jwt-key
            - name: Jwt__Issuer
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: Jwt__Issuer
            - name: Jwt__Audience
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: Jwt__Audience