apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

labels:
  - pairs:
      environment: production
      managed-by: k3s
    includeSelectors: true

namePrefix: prod-

replicas:
  - name: turboapi-auth
    count: 1
  - name: turboapi-geo
    count: 1
  - name: turboapi-activity
    count: 1
  - name: kafka
    count: 1

images:
  - name: turboapi-auth
    newName: my-registry.example.com/turboapi-auth
    newTag: v0.0.1
  - name: turboapi-geo
    newName: my-registry.example.com/turboapi-geo
    newTag: v0.0.1
  - name: turboapi-activity
    newName: my-registry.example.com/turboapi-activity
    newTag: v0.0.1
  - name: turboapi-auth-migration
    newName: my-registry.example.com/turboapi-auth-migration
    newTag: v0.0.1
  - name: turboapi-geo-migration
    newName: my-registry.example.com/turboapi-geo-migration
    newTag: v0.0.1
  - name: turboapi-activity-migration
    newName: my-registry.example.com/turboapi-activity-migration
    newTag: v0.0.1