FROM flyway/flyway:latest

ARG SERVICE_NAME

# Copy SQL scripts based on SERVICE_NAME argument
COPY ./Turboapi-${SERVICE_NAME}/db/migrations/ /flyway/sql/

# Copy the entrypoint script
COPY migrations/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]