# Auth service with lightweight db check and migration init containers
apiVersion: apps/v1
kind: Deployment
metadata:
  name: turboapi-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: turboapi-auth
  template:
    metadata:
      labels:
        app: turboapi-auth
    spec:
      initContainers:
        # First init container: check if database is up and create it if it doesn't exist
        - name: auth-db-check
          image: jbergknoff/postgresql-client
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c']
          args:
            - |
              # Wait for the database to be ready
              until psql "postgresql://$DB_USER:$DB_PASSWORD@auth-db:5432/postgres" -c '\q'; do
                echo "Waiting for auth-db to be ready...";
                sleep 2;
              done;
              
              # Check if our database exists
              echo "Checking if database exists...";
              if ! psql "postgresql://$DB_USER:$DB_PASSWORD@auth-db:5432/postgres" -tAc "SELECT 1 FROM pg_database WHERE datname='auth'" | grep -q 1; then
                echo "Database does not exist. Creating database auth...";
                psql "postgresql://$DB_USER:$DB_PASSWORD@auth-db:5432/postgres" -c "CREATE DATABASE auth";
                echo "Database auth created successfully.";
              else
                echo "Database auth already exists.";
              fi
          env:
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: postgres-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: postgres-password
        # Second init container: run migrations
        - name: auth-db-migration
          image: turboapi-auth-migration:latest
          env:
            - name: DB_HOST
              value: "auth-db"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "auth"
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: postgres-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: postgres-password
      containers:
        - name: turboapi-auth
          image: turboapi-auth:latest
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ASPNETCORE_ENVIRONMENT
            - name: ConnectionStrings__DefaultConnection
              value: "Host=auth-db;Port=5432;Database=auth;Username=$(DB_USER);Password=$(DB_PASSWORD)"
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: postgres-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: postgres-password
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector:4317"
            - name: OTEL_SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: OTEL_SERVICE_NAME_AUTH
            - name: Kafka__BootstrapServers
              value: "kafka:29092"
---
# Geo service with lightweight db check and migration init containers
apiVersion: apps/v1
kind: Deployment
metadata:
  name: turboapi-geo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: turboapi-geo
  template:
    metadata:
      labels:
        app: turboapi-geo
    spec:
      initContainers:
        # First init container: check if database is up and create it if it doesn't exist
        - name: geo-db-check
          image: jbergknoff/postgresql-client
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c']
          args:
            - |
              # Wait for the database to be ready
              until psql "postgresql://$DB_USER:$DB_PASSWORD@geo-db:5432/postgres" -c '\q'; do
                echo "Waiting for geo-db to be ready...";
                sleep 2;
              done;
              
              # Check if our database exists
              echo "Checking if database exists...";
              if ! psql "postgresql://$DB_USER:$DB_PASSWORD@geo-db:5432/postgres" -tAc "SELECT 1 FROM pg_database WHERE datname='geo'" | grep -q 1; then
                echo "Database does not exist. Creating database geo...";
                psql "postgresql://$DB_USER:$DB_PASSWORD@geo-db:5432/postgres" -c "CREATE DATABASE geo";
                echo "Database geo created successfully.";
              else
                echo "Database geo already exists.";
              fi
          env:
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: postgres-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: postgres-password
        # Second init container: run migrations
        - name: geo-db-migration
          image: turboapi-geo-migration:latest
          env:
            - name: DB_HOST
              value: "geo-db"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "geo"
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: postgres-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: postgres-password
      containers:
        - name: turboapi-geo
          image: turboapi-geo:latest
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ASPNETCORE_ENVIRONMENT
            - name: ConnectionStrings__DefaultConnection
              value: "Host=geo-db;Port=5432;Database=geo;Username=$(DB_USER);Password=$(DB_PASSWORD)"
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: postgres-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: postgres-password
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector:4317"
            - name: OTEL_SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: OTEL_SERVICE_NAME_GEO
            - name: Kafka__BootstrapServers
              value: "kafka:29092"
---
# Activity service with lightweight db check and migration init containers
apiVersion: apps/v1
kind: Deployment
metadata:
  name: turboapi-activity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: turboapi-activity
  template:
    metadata:
      labels:
        app: turboapi-activity
    spec:
      initContainers:
        # First init container: check if database is up and create it if it doesn't exist
        - name: activity-db-check
          image: jbergknoff/postgresql-client
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c']
          args:
            - |
              # Wait for the database to be ready
              until psql "postgresql://$DB_USER:$DB_PASSWORD@activity-db:5432/postgres" -c '\q'; do
                echo "Waiting for activity-db to be ready...";
                sleep 2;
              done;
              
              # Check if our database exists
              echo "Checking if database exists...";
              if ! psql "postgresql://$DB_USER:$DB_PASSWORD@activity-db:5432/postgres" -tAc "SELECT 1 FROM pg_database WHERE datname='activity'" | grep -q 1; then
                echo "Database does not exist. Creating database activity...";
                psql "postgresql://$DB_USER:$DB_PASSWORD@activity-db:5432/postgres" -c "CREATE DATABASE activity";
                echo "Database activity created successfully.";
              else
                echo "Database activity already exists.";
              fi
          env:
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: postgres-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: postgres-password
        # Second init container: run migrations
        - name: activity-db-migration
          image: turboapi-activity-migration:latest
          env:
            - name: DB_HOST
              value: "activity-db"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "activity"
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: postgres-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: postgres-password
      containers:
        - name: turboapi-activity
          image: turboapi-activity:latest
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ASPNETCORE_ENVIRONMENT
            - name: ConnectionStrings__DefaultConnection
              value: "Host=activity-db;Port=5432;Database=activity;Username=$(DB_USER);Password=$(DB_PASSWORD)"
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: postgres-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: postgres-password
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector:4317"
            - name: OTEL_SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: OTEL_SERVICE_NAME_ACTIVITY
            - name: Kafka__BootstrapServers
              value: "kafka:29092"