# ConfigMaps
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  postgres-user: "postgres"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  OTEL_SERVICE_NAME_AUTH: "turboapi-auth"
  OTEL_SERVICE_NAME_GEO: "turboapi-geo"
  OTEL_SERVICE_NAME_ACTIVITY: "turboapi-activity"
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix
spec:
  stripPrefix:
    prefixes:
      - /auth
      - /geo
      - /activity