apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - persistent-volumes.yaml
  - config.yaml
  - kafka.yaml
  - databases.yaml
  - applications.yaml
  - services.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: turboapi
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: true