# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Build and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Install Flyway
      run: |
        wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/7.7.0/flyway-commandline-7.7.0-linux-x64.tar.gz | tar xvz
        sudo mv flyway-7.7.0 /usr/local/flyway
        sudo ln -s /usr/local/flyway/flyway /usr/local/bin/flyway
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test activity
      working-directory: ./Turboapi-activity
      run: dotnet test --no-build --verbosity normal
    - name: Test auth
      working-directory: ./Turboapi-auth
      run: dotnet test --no-build --verbosity normal
    - name: Test geo
      working-directory: ./Turboapi-geo
      run: dotnet test --no-build --verbosity normal
    - name: Test events
      working-directory: ./Turbo-event
      run: dotnet test --no-build --verbosity normal
    - name: Test data
      working-directory: ./Turbo-pg-data
      run: dotnet test --no-build --verbosity normal
